# Only for 社团Battle！ with utf-8
# 游戏基本设置

MusicVolume: 0.800000012
SoundEffectVolume: 0.800000012
fullscreenMode: Windowed
resolution:
  width: 1280
  height: 720
  refreshRate: 60
sync: false
antiAliasing: 1
dithering: false
showFps: true
showConsole: true
